### ISSUE TITLE
Bug:使用文档使用插件选择自定义emoji时，点击emoji无法召唤弹窗

### ISSUE THREAD

**Issue by lovedreamms** [zuoez02/siyuan-plugin-emoji-enhance#1]
![image](https://github.com/zuoez02/siyuan-plugin-emoji-enhance/assets/122292012/e882d3d8-3720-4c62-ba82-898a8708b7ef)
点击狗头无法召唤弹窗,狗头是通过链接下载的B站emoji，
![image](https://github.com/zuoez02/siyuan-plugin-emoji-enhance/assets/122292012/731f708a-ee1b-4fdc-abb5-a9d57c24e949)
正常内置的emoji可以通过点击emoji召唤弹窗

**Comment by zuoez02** [comment]
已知的思源的bug，不是插件的问题，估计下个版本就好了吧
